### ISSUE TITLE
Which software licenses is this compatible with ?

### ISSUE THREAD

**Issue by wmealing** [emctague/honest-development#3]
I noticed you called this a license, which has some very specific legal ramifications if agreed to.  I _think_ that this may be GPL incompatible if it is a "license" as such due to its additional restrictions (as specified as a restriction in the readme.md)

IANAL, but you may wish to throw this over to the FSF for consideration as of what to call it (license may be the wrong word) and if which software licenses this is compatible with.

I'm not trying to be a pedant, it just may end up in a wierd spot and finding that out earlier is better than later.

Thanks.

**Comment by emctague** [comment]
It's not really supposed to be a license, but I might have messed up
somewhere and called it that, so I should probably fix that. Where did you
see that wording?

**Comment by emctague** [comment]
Fixed the bad wording.

**Comment by wmealing** [comment]
Thanks!
